package org.machinemc.primallib.generator;

import com.google.gson.JsonObject;
import org.machinemc.primallib.version.ProtocolVersion;

/**
 * Represents a data generator.
 */
public interface DataGenerator {

    /**
     * Returns name of this generator.
     *
     * @return name of the generator
     */
    String getName();

    /**
     * Returns protocol version of this generator.
     *
     * @return protocol version
     */
    ProtocolVersion getVersion();

    /**
     * Returns generated data in form of a json object.
     *
     * @return data generated by this generator
     */
    JsonObject getData();

    /**
     * Runs the data generator.
     */
    void run() throws Exception;

}
